export const BaseURL = "http://ergast.com/api/f1/current/"
export const ResultsURLSuffix = "last/results.json"
export const DriverStandingsSuffix = "driverStandings.json"
export const ConstructorStandingsSuffix = "constructorStandings.json"
export const BackgroundColorSplash = "#282c34"